#include <syslog.h>
int main(int argc, char **argv)
{

	openlog("test", LOG_CONS | LOG_PID, LOG_LOCAL1);

	syslog(LOG_LOCAL1 | LOG_INFO, "This is a syslog test message generated by program '%s'n", argv[0]);

	closelog();
	return 0;

}


